exchange.api.key=3a0a2cb06fbb11152b91a212
quarkus.rest-client."org.acme.clients.ExchangeRateClient".url=https://v6.exchangerate-api.com
quarkus.rest-client.exchange.api.url=https://v6.exchangerate-api.com
quarkus.rest-client.exchange.api.scope=jakarta.inject.Singleton