exchange.api.key=3a0a2cb06fbb11152b91a212
quarkus.rest-client."org.acme.clients.exchangeapi.ExchangeRateClient".url=https://v6.exchangerate-api.com
quarkus.rest-client."org.acme.clients.exchangeapi.ExchangeRateClient".scope=jakarta.inject.Singleton